### PR TITLE
Add support for Symfony 5

### PR DESCRIPTION
**Pull request by bobdenotter**
This allows the package to be used on Symfony 5. It works with the included tests, as well as some preliminary monkey-testing by me. 🙈

### CODE REVIEW

**Comment by bobdenotter** [comment]
#SymfonyHackday <- for stats

**Comment by antishov** [comment]
Thanks for your PR

**Comment by bobdenotter** [comment]
Hi @antishov, thanks for merging! 

I agree with @COil : If you could tag a 0.0.1 release, that'd be great. :-)

**Comment by antishov** [comment]
Hi. v1.4.1 has been released

**Pull request merged**
